version: '3.7'

services:
  spark-master:
    image: manisekhar/twtanalysis:spkimg
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "4040:4040"
      - "9090:8080"
      - "7077:7077"
    networks:
       mynet:
          ipv4_address: 172.78.1.10

  spark-worker-1:
    image: manisekhar/twtanalysis:spkimg
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-2:
    image: manisekhar/twtanalysis:spkimg
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  
  sentiment-consumer:
    image: manisekhar/twtanalysis:sentimentconsumer
    depends_on:
      - spark-master

  server:
    image: manisekhar/twtanalysis:server
    depends_on:
      - spark-master
    ports:
      - "9999:9999"

networks:
    mynet:
      ipam:
        driver: default
        config:
          - subnet: 172.78.0.0/16
